### ISSUE TITLE
Fail to create interpreter, cause: java.lang.ClassNotFoundException: org.apache.zeppelin.python.IPythonInterpreter

### ISSUE THREAD

**Issue by StrongestNumber9** [teragrep/zep_01#14]
```python
%python
import sys
import datetime
import socket
import getpass
import numpy

print(sys.version)
print(numpy)
print(socket.gethostname())
print(getpass.getuser())
print(datetime.datetime.now())
```

-->

```
java.lang.RuntimeException: Fail to create interpreter, cause: java.lang.ClassNotFoundException: org.apache.zeppelin.python.IPythonInterpreter
	at org.apache.zeppelin.interpreter.remote.PooledRemoteClient.callRemoteFunction(PooledRemoteClient.java:119)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterProcess.callRemoteFunction(RemoteInterpreterProcess.java:100)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreter.internal_create(RemoteInterpreter.java:159)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreter.open(RemoteInterpreter.java:126)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreter.getFormType(RemoteInterpreter.java:271)
	at org.apache.zeppelin.notebook.Paragraph.jobRun(Paragraph.java:438)
	at org.apache.zeppelin.notebook.Paragraph.jobRun(Paragraph.java:69)
	at org.apache.zeppelin.scheduler.Job.run(Job.java:172)
	at org.apache.zeppelin.scheduler.AbstractScheduler.runJob(AbstractScheduler.java:132)
	at org.apache.zeppelin.scheduler.RemoteScheduler$JobRunner.run(RemoteScheduler.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by StrongestNumber9** [comment]
Seems like the tests will also crash if enabled (issue #15 related) to

```

Tests in error: 
  PythonInterpreterTest.setUp:63 » Interpreter org.apache.zeppelin.interpreter.I...
  PythonInterpreterTest.setUp:63 » Interpreter org.apache.zeppelin.interpreter.I...
  PythonInterpreterTest.setUp:63 » Interpreter org.apache.zeppelin.interpreter.I...
  PythonInterpreterTest.setUp:63 » Interpreter org.apache.zeppelin.interpreter.I...
  PythonInterpreterTest.setUp:63 » Interpreter org.apache.zeppelin.interpreter.I...
  PythonInterpreterPandasSqlTest.setUp:107 » Interpreter Fail to open PythonInte...
  PythonInterpreterPandasSqlTest.setUp:107 » Interpreter Fail to open PythonInte...
  PythonInterpreterPandasSqlTest.setUp:107 » Interpreter Fail to open PythonInte...
  PythonInterpreterPandasSqlTest.setUp:107 » Interpreter Fail to open PythonInte...
  PythonInterpreterPandasSqlTest.setUp:107 » Interpreter Fail to open PythonInte...
  PythonInterpreterPandasSqlTest.setUp:107 » Interpreter Fail to open PythonInte...
  PythonInterpreterPandasSqlTest.setUp:107 » Interpreter Fail to open PythonInte...
  PythonInterpreterPandasSqlTest.setUp:107 » Interpreter Fail to open PythonInte...
  PythonInterpreterPandasSqlTest.setUp:107 » Interpreter Fail to open PythonInte...
  PythonInterpreterPandasSqlTest.setUp:107 » Interpreter Fail to open PythonInte...
  PythonInterpreterMatplotlibTest.setUp:74 » Interpreter Fail to open PythonInte...
  PythonInterpreterMatplotlibTest.setUp:74 » Interpreter Fail to open PythonInte...
  PythonInterpreterMatplotlibTest.setUp:74 » Interpreter Fail to open PythonInte...
  PythonInterpreterMatplotlibTest.setUp:74 » Interpreter Fail to open PythonInte...
```

**Comment by StrongestNumber9** [comment]
Seems like one of the issues are old py4j versions, ~~test currently running~~ it is the culprit!

Reference https://bugzilla.redhat.com/show_bug.cgi?id=1791969
