### ISSUE TITLE
zeppelin-server tests do not seem to be idemptotent

### ISSUE THREAD

**Issue by StrongestNumber9** [teragrep/zep_01#34]
Edit: They are currently `@Ignore`'d and needs to be re-enabled via #59 

```sh
[ERROR]   NotebookRestApiTest.testRunNoteWithParams:456 » NotePathAlreadyExists Note '/note1' existed
[ERROR]   NotebookRestApiTest.testRunParagraphJob:147 » NotePathAlreadyExists Note '/note1' existed
[ERROR]   NotebookRestApiTest.testRunParagraphSynchronously:185 » NotePathAlreadyExists Note '/note1' existed
[ERROR]   NotebookRestApiTest.testRunWithServerRestart:701 » NotePathAlreadyExists Note '/note1' existed
[ERROR]   NotebookRestApiTest.testUpdateParagraphConfig:623 » NotePathAlreadyExists Note '/note1' existed
```

```sh
[ERROR] org.apache.zeppelin.rest.NotebookRestApiTest.testRunWithServerRestart -- Time elapsed: 0.001 s <<< ERROR!
org.apache.zeppelin.notebook.exception.NotePathAlreadyExistsException: Note '/note1' existed
        at org.apache.zeppelin.notebook.NoteManager.addOrUpdateNoteNode(NoteManager.java:124)
        at org.apache.zeppelin.notebook.NoteManager.addNote(NoteManager.java:196)
        at org.apache.zeppelin.notebook.Notebook.createNote(Notebook.java:255)
        at org.apache.zeppelin.notebook.Notebook.createNote(Notebook.java:236)
        at org.apache.zeppelin.notebook.Notebook.createNote(Notebook.java:203)
        at org.apache.zeppelin.rest.NotebookRestApiTest.testRunWithServerRestart(NotebookRestApiTest.java:701)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
```

Either something fails or they just don't get cleaned up

**Comment by StrongestNumber9** [comment]
Command: `JAVA_HOME=/usr/lib/jvm/java-11-openjdk mvn -Pintegration clean package 2>&1` tee'd to a file

All subsequent runs gives different failures in different tests

First run:

```
[ERROR] Errors:
[ERROR]   ZeppelinRestApiTest.testListNotes:415->AbstractTestRestApi.httpGet:374->AbstractTestRestApi.httpGet:378->AbstractTestRestApi.httpGet:392 » HttpHostConnect Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
[ERROR]   ZeppelinRestApiTest.testMoveParagraph:868 » RejectedExecution Task org.apache.zeppelin.notebook.NoteEventAsyncListener$EventHandling@286b39c2 rejected from java.util.concurrent.ThreadPoolExecutor@5432050b[Terminated, pool size = 0, active threads = 0, queued tasks = 0, \
completed tasks = 41]
[ERROR]   ZeppelinRestApiTest.testNoteCreateNoName:137->testNoteCreate:194->AbstractTestRestApi.httpPost:415->AbstractTestRestApi.httpPost:431 » HttpHostConnect Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
[ERROR]   ZeppelinRestApiTest.testNoteCreateWithName:132->testNoteCreate:194->AbstractTestRestApi.httpPost:415->AbstractTestRestApi.httpPost:431 » HttpHostConnect Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
[ERROR]   ZeppelinRestApiTest.testNoteCreateWithParagraphs:151->AbstractTestRestApi.httpPost:415->AbstractTestRestApi.httpPost:431 » HttpHostConnect Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
[ERROR]   ZeppelinRestApiTest.testNoteJobs:436 » RejectedExecution Task org.apache.zeppelin.notebook.NoteEventAsyncListener$EventHandling@11653e3b rejected from java.util.concurrent.ThreadPoolExecutor@5432050b[Terminated, pool size = 0, active threads = 0, queued tasks = 0, compl\
eted tasks = 41]
[ERROR]   ZeppelinRestApiTest.testRegressionZEPPELIN_527:690 » RejectedExecution Task org.apache.zeppelin.notebook.NoteEventAsyncListener$EventHandling@16fe9c29 rejected from java.util.concurrent.ThreadPoolExecutor@5432050b[Terminated, pool size = 0, active threads = 0, queued ta\
sks = 0, completed tasks = 41]
[ERROR]   ZeppelinRestApiTest.testRunParagraphWithParams:551 » RejectedExecution Task org.apache.zeppelin.notebook.NoteEventAsyncListener$EventHandling@1eea9d2d rejected from java.util.concurrent.ThreadPoolExecutor@5432050b[Terminated, pool size = 0, active threads = 0, queued ta\
sks = 0, completed tasks = 41]
[ERROR]   ZeppelinRestApiTest.testTitleSearch:935 » RejectedExecution Task org.apache.zeppelin.notebook.NoteEventAsyncListener$EventHandling@7808fb9 rejected from java.util.concurrent.ThreadPoolExecutor@5432050b[Terminated, pool size = 0, active threads = 0, queued tasks = 0, com\
pleted tasks = 41]
[ERROR]   ZeppelinRestApiTest.testUpdateParagraph:783 » RejectedExecution Task org.apache.zeppelin.notebook.NoteEventAsyncListener$EventHandling@6e6fce47 rejected from java.util.concurrent.ThreadPoolExecutor@5432050b[Terminated, pool size = 0, active threads = 0, queued tasks = 0\
, completed tasks = 41]
```

Second run
```
[ERROR] Errors:
[ERROR]   NotebookRestApiTest.testRunNoteNonBlocking_Isolated:449 » RejectedExecution Task org.apache.zeppelin.notebook.NoteEventAsyncListener$EventHandling@534ca02b rejected from java.util.concurrent.ThreadPoolExecutor@29a23c3d[Terminated, pool size = 0, active threads = 0, queu\
ed tasks = 0, completed tasks = 35]
[ERROR]   NotebookRestApiTest.testRunNoteWithParams:458 » RejectedExecution Task org.apache.zeppelin.notebook.NoteEventAsyncListener$EventHandling@5173200b rejected from java.util.concurrent.ThreadPoolExecutor@29a23c3d[Terminated, pool size = 0, active threads = 0, queued tasks =\
 0, completed tasks = 35]
[ERROR]   NotebookRestApiTest.testRunParagraphJob:148 » NotePathAlreadyExists Note '/note1' existed
[ERROR]   NotebookRestApiTest.testRunParagraphSynchronously:186 » NotePathAlreadyExists Note '/note1' existed
[ERROR]   NotebookRestApiTest.testRunWithServerRestart:703 » NotePathAlreadyExists Note '/note1' existed
[ERROR]   NotebookRestApiTest.testUpdateParagraphConfig:625 » NotePathAlreadyExists Note '/note1' existed
[ERROR]   ZeppelinRestApiTest.testListNotes:415->AbstractTestRestApi.httpGet:374->AbstractTestRestApi.httpGet:378->AbstractTestRestApi.httpGet:392 » HttpHostConnect Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
[ERROR]   ZeppelinRestApiTest.testMoveParagraph:868 » RejectedExecution Task org.apache.zeppelin.notebook.NoteEventAsyncListener$EventHandling@17ae7628 rejected from java.util.concurrent.ThreadPoolExecutor@1136b469[Terminated, pool size = 0, active threads = 0, queued tasks = 0, \
completed tasks = 41]
[ERROR]   ZeppelinRestApiTest.testNoteCreateNoName:137->testNoteCreate:194->AbstractTestRestApi.httpPost:415->AbstractTestRestApi.httpPost:431 » HttpHostConnect Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
[ERROR]   ZeppelinRestApiTest.testNoteCreateWithName:132->testNoteCreate:194->AbstractTestRestApi.httpPost:415->AbstractTestRestApi.httpPost:431 » HttpHostConnect Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
[ERROR]   ZeppelinRestApiTest.testNoteCreateWithParagraphs:151->AbstractTestRestApi.httpPost:415->AbstractTestRestApi.httpPost:431 » HttpHostConnect Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
[ERROR]   ZeppelinRestApiTest.testNoteJobs:436 » RejectedExecution Task org.apache.zeppelin.notebook.NoteEventAsyncListener$EventHandling@511d5d04 rejected from java.util.concurrent.ThreadPoolExecutor@1136b469[Terminated, pool size = 0, active threads = 0, queued tasks = 0, compl\
eted tasks = 41]
[ERROR]   ZeppelinRestApiTest.testRegressionZEPPELIN_527:690 » RejectedExecution Task org.apache.zeppelin.notebook.NoteEventAsyncListener$EventHandling@5328a9c1 rejected from java.util.concurrent.ThreadPoolExecutor@1136b469[Terminated, pool size = 0, active threads = 0, queued ta\
sks = 0, completed tasks = 41]
[ERROR]   ZeppelinRestApiTest.testRunParagraphWithParams:551 » RejectedExecution Task org.apache.zeppelin.notebook.NoteEventAsyncListener$EventHandling@715fb77 rejected from java.util.concurrent.ThreadPoolExecutor@1136b469[Terminated, pool size = 0, active threads = 0, queued tas\
ks = 0, completed tasks = 41]
[ERROR]   ZeppelinRestApiTest.testTitleSearch:935 » RejectedExecution Task org.apache.zeppelin.notebook.NoteEventAsyncListener$EventHandling@3e9803c2 rejected from java.util.concurrent.ThreadPoolExecutor@1136b469[Terminated, pool size = 0, active threads = 0, queued tasks = 0, co\
mpleted tasks = 41]
[ERROR]   ZeppelinRestApiTest.testUpdateParagraph:783 » RejectedExecution Task org.apache.zeppelin.notebook.NoteEventAsyncListener$EventHandling@60921b21 rejected from java.util.concurrent.ThreadPoolExecutor@1136b469[Terminated, pool size = 0, active threads = 0, queued tasks = 0\
, completed tasks = 41]
```

Third and fourth run gave the same errors
```
[ERROR] Failures:
[ERROR]   NotebookRestApiTest.testRunNoteNonBlocking_Isolated:440 expected:<FINISHED> but was:<ABORT>
[ERROR] Errors:
[ERROR]   NotebookRestApiTest.testRunNoteWithParams:476->AbstractTestRestApi.httpPost:415->AbstractTestRestApi.httpPost:431 » NoHttpResponse localhost:8080 failed to respond
[ERROR]   NotebookRestApiTest.testRunParagraphJob:154->AbstractTestRestApi.httpPost:415->AbstractTestRestApi.httpPost:431 » HttpHostConnect Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
[ERROR]   NotebookRestApiTest.testRunParagraphSynchronously:197->AbstractTestRestApi.httpPost:415->AbstractTestRestApi.httpPost:431 » HttpHostConnect Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
[ERROR]   NotebookRestApiTest.testRunWithServerRestart:720->AbstractTestRestApi.httpPost:415->AbstractTestRestApi.httpPost:431 » HttpHostConnect Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
[ERROR]   NotebookRestApiTest.testUpdateParagraphConfig:632->AbstractTestRestApi.httpPut:437->AbstractTestRestApi.httpPut:449 » HttpHostConnect Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
```

Fifth run
```
[ERROR] Errors: 
[ERROR]   NotebookRestApiTest.testRunNoteNonBlocking_Isolated:449 » RejectedExecution Task org.apache.zeppelin.notebook.NoteEventAsyncListener$EventHandling@6ecd665 rejected from java.util.concurrent.ThreadPoolExecutor@45394b31[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 35]
[ERROR]   NotebookRestApiTest.testRunNoteWithParams:458 » RejectedExecution Task org.apache.zeppelin.notebook.NoteEventAsyncListener$EventHandling@4d847d32 rejected from java.util.concurrent.ThreadPoolExecutor@45394b31[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 35]
[ERROR]   NotebookRestApiTest.testRunParagraphJob:148 » NotePathAlreadyExists Note '/note1' existed
[ERROR]   NotebookRestApiTest.testRunParagraphSynchronously:186 » NotePathAlreadyExists Note '/note1' existed
[ERROR]   NotebookRestApiTest.testRunWithServerRestart:703 » NotePathAlreadyExists Note '/note1' existed
[ERROR]   NotebookRestApiTest.testUpdateParagraphConfig:625 » NotePathAlreadyExists Note '/note1' existed
[ERROR]   ZeppelinRestApiTest.testNoteJobs:485 » RejectedExecution Task org.apache.zeppelin.notebook.NoteEventAsyncListener$EventHandling@72ba28ee rejected from java.util.concurrent.ThreadPoolExecutor@2e3a5237[Shutting down, pool size = 1, active threads = 1, queued tasks = 11, completed tasks = 44]
[ERROR]   ZeppelinRestApiTest.testRegressionZEPPELIN_527:690 » RejectedExecution Task org.apache.zeppelin.notebook.NoteEventAsyncListener$EventHandling@715fb77 rejected from java.util.concurrent.ThreadPoolExecutor@2e3a5237[Shutting down, pool size = 1, active threads = 1, queued tasks = 11, completed tasks = 44]
[ERROR]   ZeppelinRestApiTest.testRunParagraphWithParams:551 » RejectedExecution Task org.apache.zeppelin.notebook.NoteEventAsyncListener$EventHandling@3e9803c2 rejected from java.util.concurrent.ThreadPoolExecutor@2e3a5237[Shutting down, pool size = 1, active threads = 1, queued tasks = 10, completed tasks = 45]
[ERROR]   ZeppelinRestApiTest.testTitleSearch:935 » RejectedExecution Task org.apache.zeppelin.notebook.NoteEventAsyncListener$EventHandling@60921b21 rejected from java.util.concurrent.ThreadPoolExecutor@2e3a5237[Shutting down, pool size = 1, active threads = 1, queued tasks = 10, completed tasks = 45]
[ERROR]   ZeppelinRestApiTest.testUpdateParagraph:783 » RejectedExecution Task org.apache.zeppelin.notebook.NoteEventAsyncListener$EventHandling@773bd77b rejected from java.util.concurrent.ThreadPoolExecutor@2e3a5237[Shutting down, pool size = 1, active threads = 1, queued tasks = 10, completed tasks = 45]
```

Executed `git clean -f -x -d -e .idea` with `mvn -Pintegration clean` and the results were

```
[ERROR] Failures: 
[ERROR]   NotebookRestApiTest.testRunNoteNonBlocking_Isolated:440 expected:<FINISHED> but was:<ABORT>
[ERROR] Errors: 
[ERROR]   NotebookRestApiTest.testRunNoteWithParams:476->AbstractTestRestApi.httpPost:415->AbstractTestRestApi.httpPost:431 » HttpHostConnect Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
[ERROR]   NotebookRestApiTest.testRunParagraphJob:154->AbstractTestRestApi.httpPost:415->AbstractTestRestApi.httpPost:431 » HttpHostConnect Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
[ERROR]   NotebookRestApiTest.testRunParagraphSynchronously:197->AbstractTestRestApi.httpPost:415->AbstractTestRestApi.httpPost:431 » HttpHostConnect Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
[ERROR]   NotebookRestApiTest.testRunWithServerRestart:720->AbstractTestRestApi.httpPost:415->AbstractTestRestApi.httpPost:431 » HttpHostConnect Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
[ERROR]   NotebookRestApiTest.testUpdateParagraphConfig:632->AbstractTestRestApi.httpPut:437->AbstractTestRestApi.httpPut:449 » HttpHostConnect Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
[ERROR]   ZeppelinRestApiTest.testListNotes:415->AbstractTestRestApi.httpGet:374->AbstractTestRestApi.httpGet:378->AbstractTestRestApi.httpGet:392 » HttpHostConnect Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
[ERROR]   ZeppelinRestApiTest.testMoveParagraph:868 » RejectedExecution Task org.apache.zeppelin.notebook.NoteEventAsyncListener$EventHandling@c3fa05a rejected from java.util.concurrent.ThreadPoolExecutor@7b44b63d[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 41]
[ERROR]   ZeppelinRestApiTest.testNoteCreateNoName:137->testNoteCreate:194->AbstractTestRestApi.httpPost:415->AbstractTestRestApi.httpPost:431 » HttpHostConnect Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
[ERROR]   ZeppelinRestApiTest.testNoteCreateWithName:132->testNoteCreate:194->AbstractTestRestApi.httpPost:415->AbstractTestRestApi.httpPost:431 » HttpHostConnect Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
[ERROR]   ZeppelinRestApiTest.testNoteCreateWithParagraphs:151->AbstractTestRestApi.httpPost:415->AbstractTestRestApi.httpPost:431 » HttpHostConnect Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
[ERROR]   ZeppelinRestApiTest.testNoteJobs:436 » RejectedExecution Task org.apache.zeppelin.notebook.NoteEventAsyncListener$EventHandling@57bd802b rejected from java.util.concurrent.ThreadPoolExecutor@7b44b63d[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 41]
[ERROR]   ZeppelinRestApiTest.testRegressionZEPPELIN_527:690 » RejectedExecution Task org.apache.zeppelin.notebook.NoteEventAsyncListener$EventHandling@5183d589 rejected from java.util.concurrent.ThreadPoolExecutor@7b44b63d[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 41]
[ERROR]   ZeppelinRestApiTest.testRunParagraphWithParams:551 » RejectedExecution Task org.apache.zeppelin.notebook.NoteEventAsyncListener$EventHandling@68e62ca4 rejected from java.util.concurrent.ThreadPoolExecutor@7b44b63d[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 41]
[ERROR]   ZeppelinRestApiTest.testTitleSearch:935 » RejectedExecution Task org.apache.zeppelin.notebook.NoteEventAsyncListener$EventHandling@11653e3b rejected from java.util.concurrent.ThreadPoolExecutor@7b44b63d[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 41]
[ERROR]   ZeppelinRestApiTest.testUpdateParagraph:783 » RejectedExecution Task org.apache.zeppelin.notebook.NoteEventAsyncListener$EventHandling@16fe9c29 rejected from java.util.concurrent.ThreadPoolExecutor@7b44b63d[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 41]
```
